import type { Metadata } from "next";
import { Inter , Rubik as FontSans  } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

const fontSans = FontSans({ subsets: ["latin"],  variable: "--font-sans", });
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toaster";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import Provider from "./state";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en" suppressHydrationWarning>
      <body id="body" className={cn("h-screen overflow-y-scroll font-sans  antialiased bg-white", fontSans.variable)}>
        <Provider>
        <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
        >
         
        {children}
        
        </ThemeProvider>
        </Provider>
        <Toaster />
      </body>
    </html>
  );
}
